import turtle as tl # pip install turtle
t = tl.Turtle()
s = tl.Screen()
s.title('Triangle')
s.cv._rootwindow.resizable(0,0)
t.fillcolor("green")
t.begin_fill()
t.color("green")
t.right(60)
t.forward(100)
t.right(120)
t.forward(100)
t.right(120)
t.forward(100)
t.end_fill()
tl.done()
